pipeline {
    agent any
    stages {
        stage('Test Docker') {
            steps {
                sh 'docker --version'
            }
        }
        stage('Docker plus jenkins') {
            steps {
                sh 'df -h'
            }
        }
    }
}
